CREATE TABLE [dbo].[Department]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Guid] UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL DEFAULT NEWID(),
	[Code] NVARCHAR(5) UNIQUE NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT(1),
	[CreateDate] DATETIME NOT NULL DEFAULT GETDATE(),
	[UpdateDate] DATETIME NULL
)